name: Update GitHub activity workflow
on:
    schedule:
        # Runs every hour at minute 0
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    update-readme-with-github-activity:
        name: Update Alex README with his GitHub activity
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jamesgeorge007/github-activity-readme@master
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              with:
                  COMMIT_MSG: "🦾 Automatically update README about my latest GitHub activity"
